services:
  api-1:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./log:/app/log
      - ./database:/app/database
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
    container_name: api-1
